name: 股票监控

on:
  schedule:
    - cron: "0 1 * * 1-5"

  workflow_dispatch:

jobs:
  stock-check:
    runs-on: ubuntu-latest

    steps:
    - name: 下载代码
      uses: actions/checkout@v4

    - name: 运行程序
      run: python stock_monitor.py
