name: 股票监控

on:
  workflow_dispatch:

jobs:
  stock-check:
    runs-on: ubuntu-latest

    steps:
      - name: 下载代码
        uses: actions/checkout@v4

      - name: 安装分析工具
        run: pip install -r requirements.txt
      - name: 运行程序
        run: python stock_monitor.py
